name: Build

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3

    - name: Setup
      run: |
        sudo apt update
        sudo apt install g++ g++-aarch64-linux-gnu g++-mingw-w64

    - name: Build Linux x86_64
      run: |
        mkdir -p dist/x86_64-linux-gnu
        g++ -std=c++17 -O3 --static main.cpp -o dist/x86_64-linux-gnu/rtlc

    - name: Build Linux aarch64
      run: |
        mkdir -p dist/aarch64-linux-gnu
        aarch64-linux-gnu-g++ -std=c++17 -O3 --static main.cpp -o dist/aarch64-linux-gnu/rtlc

    - name: Build Windows i686
      run: |
        mkdir -p dist/i686-w64-mingw32
        i686-w64-mingw32-g++ -std=c++17 -O3 --static main.cpp -o dist/i686-w64-mingw32/rtlc.exe

    - name: Build Windows x86_64
      run: |
        mkdir -p dist/x86_64-w64-mingw32
        x86_64-w64-mingw32-g++ -std=c++17 -O3 --static main.cpp -o dist/x86_64-w64-mingw32/rtlc.exe

    - name: Publish Linux x86_64
      uses: actions/upload-artifact@master
      with:
        name: x86_64-linux-gnu
        path: dist/x86_64-linux-gnu

    - name: Publish Linux aarch64
      uses: actions/upload-artifact@master
      with:
        name: aarch64-linux-gnu
        path: dist/aarch64-linux-gnu

    - name: Publish Windows i686
      uses: actions/upload-artifact@master
      with:
        name: i686-w64-mingw32
        path: dist/i686-w64-mingw32

    - name: Publish Windows x86_64
      uses: actions/upload-artifact@master
      with:
        name: x86_64-w64-mingw32
        path: dist/x86_64-w64-mingw32

  build-mac:
    runs-on: macos-11

    steps:
    - uses: actions/checkout@v3

    - name: Build macOS x86_64
      run: |
        mkdir -p dist/x86_64-apple-darwin
        g++ -std=c++17 -O3 main.cpp -o dist/x86_64-apple-darwin/rtlc
    - name: Publish macOS x86_64
      uses: actions/upload-artifact@master
      with:
        name: x86_64-apple-darwin
        path: dist/x86_64-apple-darwin
